### ISSUE TITLE
PivotTable CellClickListener description

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/documentation#101]
## Added methods

- `addCellClickListener` - Adds a listener to the pivot table cell click events. Fired only for table renderers (table, heatmap, table barchart, col heatmap, row heatmap).
- `removeCellClickListener` - remove previously added listener

## Sample Code:

```
pivotTable.addCellClickListener(event -> {
    showNotification("Value: " + event.getValue() + "\n" +
            "filters: " + event.getFilters());
});
```

**Comment by oshiryaeva** [comment]
Fixed in #100
