### ISSUE TITLE
Nginx proxy configuration does not work for UberJar

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#152]
### Environment

- Documentation version: 6.9
- Part of the documentation: Manual 
- Existing page: https://doc.cuba-platform.com/manual-6.9/proxy_configuration_tomcat.html

### Description of the bug or enhancement

For some reason Nginx should have / at the end of location to work with Uber Jar properly.

Does not work 
```
location / app {

}
```

Works:
```
location /app/ {

}
```

**Comment by rapekas** [comment]
Take into account https://github.com/cuba-platform/documentation/issues/123
