### ISSUE TITLE
Entity states and em.merge

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#18]
All newbie developers and many experienced ones don't understand the meaning of managed entity state and purpose of `em.merge`. For them em.merge call is "save entity changes to DB", like `em.save()`.
Existing documentation pages ([1](https://doc.cuba-platform.com/manual-6.8/entity_states.html), [2](https://doc.cuba-platform.com/manual-6.8/entityManager.html)) are not enough. Too brief, people just don't get the sense without real code.

TODO: add examples, recommended scenarios, explanations of side effects.

What can be added:
- explanation of what exactly `em.merge` is doing under the hood. Side effects: optimistic lock checking. When we need to use `em.merge` and when we don't need it. Code example of justified `em.merge` usage.
- code example of `em.reload` usage.
- code example for this sentence:
> Any changes of the instance in `Managed` state will be saved to the database when the transaction that the EntityManager belongs to is committed.

**Comment by knstvk** [comment]
We'll promote DataManager.
