### ISSUE TITLE
Bean validation: @Valid annotation should present if method prameter or return value validation is required

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/documentation#198]
See the Hibernate validator documentation: https://docs.jboss.org/hibernate/validator/5.4/reference/en-US/html_single/#_cascaded_validation
See the forum: https://www.cuba-platform.com/discuss/t/validation-in-middleware-services-called-from-rest-api/5987

**Comment by knstvk** [comment]
See comment in the commit.
