### ISSUE TITLE
Need to add Client test initial configuration description to docs (and maybe to CLI)

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/documentation#210]
### Environment

- Documentation version: 6.9.5 
- Part of the documentation: Manual - Client Tier Integration Tests
- Existing page: https://doc.cuba-platform.com/manual-6.9/integration_tests_client.html

### Description of the bug or enhancement
We need to specify how to add client test dependencies like it was described here: https://www.cuba-platform.com/discuss/t/where-to-find-cubaclienttestcase/46/2

**Comment by knstvk** [comment]
Will be done in #326
