### ISSUE TITLE
Optimistic locking for REST API

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/documentation#221]
### Environment

- Documentation version: 6.10
- Part of the documentation: Manual,  REST API

### Description of the bug or enhancement
Optimistic locking is enabled while setting property:
`cuba.rest.optimisticLockingEnabled` in the REST properties.
Default value is false.
if the version isn't specified in the JSON, optimistic locking doesn't work.

Original issue: cuba-platform/cuba#1196

**Comment by oshiryaeva** [comment]
@andreysubbotin please take a look [at the commit](https://github.com/cuba-platform/restapi-docs/commit/caa6089794c44a314e74e5d1ca89ca79718815cc)
