### ISSUE TITLE
Document min/max APIs for Window and ScrollBoxLayout

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#239]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual 

### Description of the bug or enhancement

See https://github.com/cuba-platform/cuba/issues/1172

**Comment by knstvk** [comment]
- Create a new section: Visual Components Library > Containers > Layout
- Move all information about layout attributes to it, including min/max sizes and examples.
