### ISSUE TITLE
Change @EventListener method modifier to protected in examples

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#241]
### Environment

- Documentation version: 6.9
- Part of the documentation: Manual 
- Existing page: https://doc.cuba-platform.com/manual-6.10/app_lifecycle_events.html

### Description of the bug or enhancement

By default Spring events require protected, package or public for `@EventListener` methods.

> org.springframework.beans.factory.BeanInitializationException: Failed to process @EventListener annotation on bean with name 'atl_PostQueueController'; nested exception is java.lang.IllegalStateException: Need to invoke method 'onAppStopped' found on proxy for target class 'PostQueueController' but cannot be delegated to target bean. Switch its visibility to package or protected. 

Let's include this as Warning to https://doc.cuba-platform.com/manual-6.10/events.html and https://doc.cuba-platform.com/manual-6.10/app_lifecycle_events.html

**Comment by oshiryaeva** [comment]
One Warning is enough, imho. These chapters are linked, anyway.
