### ISSUE TITLE
Document UiExceptionHandler interface - replacement for GenericExceptionHandler

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#245]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual

### Description of the bug or enhancement

UiExceptionHandler is replacement for GenericExceptionHandler, has the same responsibility as the old interface, but uses new UI API.

See also https://github.com/cuba-platform/cuba/issues/1486

**Comment by knstvk** [comment]
https://doc.cuba-platform.com/manual-7.0/exceptionHandlers.html
