### ISSUE TITLE
Add information about Hot-deploy of portal templates to the docs

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/documentation#247]
#### Environment

- Documentation version: 6.9
- Part of the documentation: Manual 
- Existing page: https://doc.cuba-platform.com/manual-6.9/hot_deploy.html

### Description of the bug 
Add the following information to the docs:
https://youtrack.cuba-platform.com/issue/STUDIO-4104
https://youtrack.cuba-platform.com/issue/PL-7229

**Comment by knstvk** [comment]
See my comment in commit.
