### ISSUE TITLE
Incorrect asciidoc formatting in FTS

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#256]
### Environment

- Documentation version:  master branch
- Part of the documentation: FTS
- Existing page: 
        documentation/content/fts/adoc/en/fts_config.adoc
      

### incorrect format 
![image](https://user-images.githubusercontent.com/1725996/48312360-579ed300-e5e8-11e8-92b6-a6cce649a3ee.png)

**Comment by lugreen** [comment]
I will fix some found simple format problem directly,   is it ok?

**Comment by knstvk** [comment]
Sure, please do.
