### ISSUE TITLE
TreeDataGrid documentation

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#260]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual 

### Description of the bug or enhancement

New UI component - TreeDataGrid: https://github.com/cuba-platform/cuba/issues/380

**Comment by oshiryaeva** [comment]
https://github.com/cuba-platform/documentation/commit/0910aa48db2a00eef4cff3ac15605492b2f69f31
