### ISSUE TITLE
Document UiComponents - replacement for ComponentsFactory

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#262]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual 

### Description of the bug or enhancement

`UiComponents` bean: https://github.com/cuba-platform/cuba/issues/1126

**Comment by oshiryaeva** [comment]
@jreznot I'll need help with [Pluggable Component Factories](https://doc.cuba-platform.com/manual-latest/pluggable_component_factories.html)

**Comment by knstvk** [comment]
https://doc.cuba-platform.com/manual-7.0/uiComponents.html
