### ISSUE TITLE
Docker tutorial does not work anymore

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#273]
### Environment

- Documentation version: 6.10
- Part of the documentation: Manual 
- Existing page: https://doc.cuba-platform.com/manual-latest-ru/docker_plugin.html

### Description of the bug or enhancement

See forum topic https://www.cuba-platform.ru/discuss/t/nerabochaya-instrukcziya-po-sozdaniyu-dockerfile/2382

Fix the tutorial with the latest gradle plugin and mention the required plugin version.

**Comment by knstvk** [comment]
The section has been removed as irrelevant.
