### ISSUE TITLE
Document application property cuba.performanceLogDisabled

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/documentation#299]
**Environment**

- 7.0 documentation version.
- Part of the documentation: Manual

**Description**

Platform issue: [#920](https://github.com/cuba-platform/cuba/issues/920)
`cuba.performanceLogDisabled` is needed to disable `PerformanceLogInterceptor`.
To disable PerformanceLogInterceptor add to `app.properties` file `cuba.performanceLogDisabled` property with value `true`. To enable it again delete this property or set value to `false`.

**Comment by knstvk** [comment]
Plz explain what PerformanceLogInterceptor is and why you may want to disable it.
