### ISSUE TITLE
Fix sample code location for screen layout rules

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#306]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual 
- Existing page: screen_layout_rules_alignment

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/1725996/50554767-dddbb980-0cfb-11e9-9f61-2a141a5018ba.png)

**Comment by BryanYin** [comment]
Hi, @knstvk , the 2nd source should be
`include::{sourcesdir}/gui_vcl/screen_layout_rules_align_2.xml[]`
Pls note the "_2" .

**Comment by knstvk** [comment]
Fixed, thanks!
