### ISSUE TITLE
Document about WindowManager  in gui_web/gui_desktop is outdated

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#327]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual 
- Existing page: gui_web/gui_desktop

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/1725996/51422495-48409500-1bea-11e9-822d-ee45080c2e17.png)

**Comment by knstvk** [comment]
Already removed in the latest version: https://doc.cuba-platform.com/manual-7.0/gui_web.html
