### ISSUE TITLE
Document about "Credits" is outdated.

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#329]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual
- Existing page: 'credits'

### Description of the bug or enhancement
Hi,
I found the  following  content seems that is outdated。
![image](https://user-images.githubusercontent.com/1725996/51461134-4d434700-1d98-11e9-8998-806634571237.png)

**Comment by knstvk** [comment]
Hi,
Why do you think it is outdated?

**Comment by lugreen** [comment]
I want view the cuba-credits.xml file when  reading the document,but i can't found the file. 
Then i explored the source code, i found that the cuba-credits.xml  is renamed. 
So i think  the doucemnt is outdated. 
![image](https://user-images.githubusercontent.com/1725996/51529830-805b0880-1e74-11e9-9402-ba2047970424.png)

Am i right?

**Comment by knstvk** [comment]
Absolutely! We'll fix it, thank you.
