### ISSUE TITLE
Inconsistent terminology  for DataStore in  Persistence.adoc

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#340]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual
- Existing page: 'Persistence.adoc'

### Description of the bug or enhancement
Hi, 
I think should use same terminology for datastore in anywhere.  
![image](https://user-images.githubusercontent.com/1725996/51589042-c1105b80-1f20-11e9-991d-b4d2f6f7d73c.png)
Am i right?

**Comment by knstvk** [comment]
We usually use "database" and "data store" interchangeably. I don't think that it can make any confusion in this section.
