### ISSUE TITLE
Problems with unique constraint violation localization

### ISSUE THREAD

**Issue by mikheev17555345** [cuba-platform/documentation#389]
### Environment

- Platform version: 6.9.1

### Description of the bug or enhancement

When trying to define a localization message for unique constraint violation it requires constraint name to be uppercase. This behavior is not documented and not logical.

**Comment by jreznot** [comment]
It is required due to deployment differences of MySQL / Oracle that can return IDS of DB objects in different case. Let's document this as requirement for DB constraint messages, so they have to be in UPPER_CASE
