### ISSUE TITLE
Get rid of REST API documentation

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/documentation#406]
### Environment

- Documentation version: 7.1
- Part of the documentation: Manual
- Existing page: [REST API](https://doc.cuba-platform.com/manual-latest/rest_api_v2.html)

### Description of the bug or enhancement

REST API is extracted as app component ([repository](https://github.com/cuba-platform/restapi)) and its documentation is moved into addon [wiki](https://github.com/cuba-platform/restapi/wiki).

So all documentation pages should be removed and link to addon and its wiki should be added

![image](https://user-images.githubusercontent.com/6183810/54802864-8f98df80-4c86-11e9-877e-5070b019df1d.png)

**Comment by zhenyazb** [comment]
already fixed in 7.1 documentation
