### ISSUE TITLE
 Add example with ContainerDataProvider and programmatic data binding

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/documentation#407]
### Environment

- Documentation version: 7.0+
- Part of the documentation: Charts
- Existing page: https://doc.cuba-platform.com/charts-7.0/chart_data_binding.html#chart_data_provider

### Description of the bug or enhancement

Add example with ContainerDataProvider and programmatic data binding.

See also https://www.cuba-platform.com/discuss/t/how-to-change-chart-datacontainer-in-v7/8608/2

**Comment by sukhova** [comment]
Commit: 204734335772173b6b0c211e482af6087b66887c
