### ISSUE TITLE
Question to report on the link...

### ISSUE THREAD

**Issue by flashcsgroups** [cuba-platform/documentation#408]
Вопрос к отчету по ссылке https://github.com/cuba-platform/documentation/blob/680267e491045ce07e87dae87100e8ba97304f46/content/reporting/source/jasper.jrxml

Как можно сформировать такую таблицу? С какими настройками? Помогите пожайлуста .

Question to report on the link https://github.com/cuba-platform/documentation/blob/680267e491045ce07e87dae87100e8ba97304f46/content/reporting/source/jasper.jrxml

How can such a table be formed? What settings? Help please .

### Environment

- Documentation version: X.Y 
- Part of the documentation: Manual 
- Existing page:

**Comment by jreznot** [comment]
Please use our forum https://www.cuba-platform.ru/discuss/ . Github issues only for problems and improvements in documentation.
