### ISSUE TITLE
Document entity bean validation in DataManager

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/documentation#420]
### Environment

- Documentation version: 7.1
- Part of the documentation: Manual
- Existing page: [DataManager](https://doc.cuba-platform.com/manual-7.0/dataManager.html), [DataManager vs. EntityManager](https://doc.cuba-platform.com/manual-7.0/dm_vs_em.html), [Running Validation](https://doc.cuba-platform.com/manual-7.0/bean_validation_running.html).

### Description of the enhancement

See original platform issue: [#1771](https://github.com/cuba-platform/cuba/issues/1771).
Since Cuba 7.1 entity bean validation enforced on `DataManager` level. It means that by default entities will be validated on commits via `DataManager`.
Added new application property `cuba.dataManagerBeanValidation` with default value `true` which toggles entity bean validation on `DataManager` level. Set this property to `false` to disable validation on `DataManager` level.
`CommitContext` now have additional property `ValidationType` (see javadocs for `CommitContext`).

**Comment by soraksh** [comment]
Added `ValidationType` and `ValidationGroups` for `DataContext.PreCommitEvent` which affects commit associated with event (will be ignored if `DataContext` is child).

**Comment by andreysubbotin** [comment]
https://github.com/cuba-platform/cuba/issues/1771#issuecomment-516855890
