### ISSUE TITLE
The description for get token for Rest API is outdate

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/documentation#428]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual
- Existing page: rest_api_v2_ex_get_token

### Description of the bug or enhancement

The description for get token for Rest API is outdate.
The password need add a prefix :{noop}
Discussion in forum: https://www.cuba-platform.com/discuss/t/geting-token-for-rest-api-throw-exception/8846/7

**Comment by gorbunkov** [comment]
Duplicates https://github.com/cuba-platform/documentation/issues/427
