### ISSUE TITLE
Add to SuggestionPickerField description and declarative example of query usage

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/documentation#430]
### Environment
- Documentation version: 7.0
- Part of the documentation: Manual
- Localization: En and Ru
- Existing page: https://doc.cuba-platform.com/manual-7.0/gui_SuggestionPickerField.html

### Description of the bug or enhancement
`SuggestionField` and `SuggestionPickerField` both have element `query` and related with it attributes. **But description added only for SuggestionField**.

We need to add the same description with example to `SuggestionPickerField`.
![image](https://user-images.githubusercontent.com/22093943/56367076-83f8f400-6205-11e9-94cb-8333f2cb0212.png)

**Comment by sukhova** [comment]
A link to the description of the _query_ element is already available for component `SuggestionPickerField`
