### ISSUE TITLE
Document InputDialog

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/documentation#431]
### Environment
- Documentation version: 7.0
- Part of the documentation: Manual

### Description of the bug or enhancement
See cuba-platform/cuba#1831

**Comment by knstvk** [comment]
Plz rename INPUT_DIALOG_APPLY_ACTION and INPUT_DIALOG_REJECT_ACTION to `INPUT_DIALOG_YES_ACTION` and `INPUT_DIALOG_NO_ACTION` respectively.
