### ISSUE TITLE
Test Reporting with LibreOffice integration with preinstalled Tomcat on Linux

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#48]
https://www.cuba-platform.com/discuss/t/deployment-and-reports-libreoffice-not-found/2933/10

**Comment by rapekas** [comment]
For Ubuntu users, who installed tomcat using apt, it is necessary to copy `~/.config/libreoffice` to $CATALINA_HOME, usually it is `/usr/share/tomcat{x}`. After that change the owner of this folder:
```
sudo mkdir /usr/share/tomcat8/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat8/.config/
sudo chown -R tomcat8.tomcat8 /usr/share/tomcat8/.config/
```
