### ISSUE TITLE
Delete the step from quick start with @NamePattern specifying  

### ISSUE THREAD

**Issue by skatova** [cuba-platform/documentation#509]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual
- Existing page: https://doc.cuba-platform.com/manual-7.0/qs_create_entities.html

### Description of the bug or enhancement
According to https://youtrack.cuba-platform.com/issue/STUDIO-6079 users don't need to specify the instance name of the Customer entity.

**Comment by zhenyazb** [comment]
Fixed in #492
