### ISSUE TITLE
Deployment and reports: Libreoffice not found

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#51]
Describe LibreOffice setup for Yarg reporting on Ubuntu
https://www.cuba-platform.com/discuss/t/deployment-and-reports-libreoffice-not-found/2933

**Comment by rapekas** [comment]
For Ubuntu users, who installed tomcat using apt, it is necessary to copy `~/.config/libreoffice` to $CATALINA_HOME, for tomcat8 it is `/usr/share/tomcat8`. After that change the owner of this folder:
```
sudo mkdir /usr/share/tomcat8/.config
sudo cp -pr ~/.config/libreoffice /usr/share/tomcat8/.config/
sudo chown -R tomcat8.tomcat8 /usr/share/tomcat8/.config/
```
