### ISSUE TITLE
Change the way of addons managing in quick starts

### ISSUE THREAD

**Issue by skatova** [cuba-platform/documentation#511]
### Environment

- Documentation version: 7.0
- Part of the documentation: Reports, bpm, fts, charts
- Existing page: https://doc.cuba-platform.com/reporting-7.0-ru/wizard.html
https://doc.cuba-platform.com/bpm-7.0-ru/qs_project_creation.html
https://doc.cuba-platform.com/charts-7.0-ru/chart_dependency.html
https://doc.cuba-platform.com/fts-7.0-ru/qs_project_setup.html

### Description of the bug or enhancement
According to https://youtrack.haulmont.com/issue/STUDIO-6415 reports, fts, charts, bpm addons managed through add-ons window

**Comment by zhenyazb** [comment]
Related to #563

**Comment by zhenyazb** [comment]
Fixed in #563
