### ISSUE TITLE
Add a web analytics code in add-ons docs

### ISSUE THREAD

**Issue by funxies** [cuba-platform/documentation#558]
This is a single issue for a few docs repositories. The list of instances to be updated:
- [Maps](https://github.com/cuba-platform/maps-docs)
- [BProc](https://github.com/cuba-platform/bproc-docs)
- [Rest API](https://github.com/cuba-platform/restapi-docs)
- [WebDAV](https://github.com/cuba-platform/webdav-docs)

The code to add (should be placed in the `<head>`):
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MH3DTWV');</script>
<!-- End Google Tag Manager -->
```

**Comment by zhenyazb** [comment]
The code has been added to the projects.
