### ISSUE TITLE
Add Installation section to the standard add-ons

### ISSUE THREAD

**Issue by zhenyazb** [cuba-platform/documentation#563]
- Documentation version: 7.0, 7.1, 7.2
- Part of the documentation: Reporting, BPM, FTS, Charts, BI Integration

### Description of the bug or enhancement
Add Installation section containing installation from the Marketplace.   
Section should go after Overview section. 
Fix links in Quick Start sections.

**Comment by zhenyazb** [comment]
#562

**Comment by knstvk** [comment]
In BI docs, replace the first item of "Adding BI to Your Application" section with the new instruction.
