### ISSUE TITLE
Improve documentation and java docs for RelativePathResource

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#61]
Java doc confuses users, because if they try to replicate the given example it will not work, as Vaadin serves static by default only under /VAADIN/ folder.
```
/**
 * A resource that is stored in the directory of your application, e.g.:
 * <code>${catalina.base}/webapps/appName/static/image.png</code>.
 */
public interface RelativePathResource extends Resource, ResourceView.HasMimeType {
    /**
     * @param path path to the resource, e.g. "static/image.png"
     * @return current RelativePathResource instance
     */
    RelativePathResource setPath(String path);

    String getPath();
}
```
Add information about default folder for static to the documentation as well.

Also add a tip to be able to define a custom folder for images. Add the following lines in app web.xml:
```
    <servlet-mapping>
        <servlet-name>default</servlet-name>
        <url-pattern>/custom_folder/*</url-pattern>
    </servlet-mapping>
```
to serve static images from custom_folder

**Comment by dtsaryov** [comment]
Related CUBA issue: cuba-platform/cuba#2667
