### ISSUE TITLE
Update the Social Login section

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/documentation#613]
### Environment

- Documentation version: 7.1
- Part of the documentation: Manual
- Existing page: [Social Login](https://doc.cuba-platform.com/manual-7.1/social_login.html)
- Relates to [cuba-platform/documentation/issues/397](https://github.com/cuba-platform/documentation/issues/397)

### Description of the bug or enhancement

Please, check the relevance of the **Social Login** section:

[GitHub Social login sample] (https://github.com/cuba-platform/sample-social-login) is based on **CUBA 6.8**

**Comment by dtsaryov** [comment]
API that is used in the sample stays the same, so we don't have to update something. The only suggestion is to add a link to our social login guide
