### ISSUE TITLE
Warning note on every "GUI Legacy API" page

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/documentation#616]
### Description of the bug or enhancement
forum: https://www.cuba-platform.com/discuss/t/version-7-0-jpql-session-parameter/8943/5?u=alexbudarov

Many people including me get tricked when using the search in the documentation and jumping into the page inside the "legacy API" chapter. The content on the page does not highlight at all that information presented is mostly useless for new projects.

Can we put some warning block or image to every sub-page inside legacy chapter, for all time as long as legacy API is supported?

![image](https://user-images.githubusercontent.com/6158807/70598481-62b99d80-1c04-11ea-94ce-e57ec797b64b.png)

**Comment by knstvk** [comment]
Let's add this at the top of each section where there is no such admonition yet:
```
[WARNING]
====
This is a legacy API. For the new API available since v.7.0, see <<gui_framework>>.
====
```
