### ISSUE TITLE
Improve "Client Tier Integration Tests" documentation

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#63]
See https://doc.cuba-platform.com/manual-6.8/integration_tests_client.html
Only setUp() method listing is brought. But it seems the whole class will be better.
![image](https://user-images.githubusercontent.com/11287637/37036999-c578b370-216a-11e8-881c-b0a2f4196c2a.png)

**Comment by knstvk** [comment]
Will be done in #326
