### ISSUE TITLE
Improve 3.2.2.3.1. Datatype Format Strings page

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/documentation#639]
### Environment
- Existing page: https://doc.cuba-platform.com/manual-7.1/datatype_format_strings.html

### Description of the bug or enhancement
That page doesn't help much, unless you have seen default values and are familiar with NumberFormat / SimpleDateFormat Java SE classes.

Studio UI also doesn't help much (yet).

My suggestions:
1) Add links to Java SE documentation:
DecimalFormat - https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html
SimpleDateFormat - https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

2) Add real examples with comments. Maybe even provide default values built-in into CUBA.
A few examples from me:
```
# comma as decimal separator
numberDecimalSeparator=,

# space as thousands grouping separator
numberGroupingSeparator = \u0020

# Always display two digits after decimal separator, e.g. for currencies
decimalFormat = #,##0.00

# disable thousands grouping separator for integers
integerFormat = #0

# United States date format
dateFormat = MM/dd/yyyy

# Russia date+time format
dateTimeFormat = dd.MM.yyyy HH:mm

# alternative displaying for boolean values
trueString = yes
falseString = no
```

**Comment by oshiryaeva** [comment]
@alexbudarov please take a look at the commit above

**Comment by alexbudarov** [comment]
@oshiryaeva 
good, but we should not suggest this as example:
> timeFormat=h:mm a

It will break TimeField components, they don't support such format.
see https://github.com/cuba-platform/cuba/issues/2347
