### ISSUE TITLE
Describe WebBrowserTools 

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/documentation#646]
### Environment
- Documentation version: 7.1

### Description of the bug or enhancement
com.haulmont.cuba.gui.WebBrowserTools looks like part of UiContext:
com.haulmont.cuba.gui.exception.UiExceptionHandler.UiContext

A bean that can be obtained in screens and used to show links.
See e.g. this forum topic: 
https://www.cuba-platform.com/discuss/t/menu-link-to-external-url-in-v7/11330/2
(and related one)

There are zero occurences of the WebBrowserTools in the developers manual's snapshot.

**Comment by zhenyazb** [comment]
fixed in #653
