### ISSUE TITLE
Make project structure more clear in Creating a GWT component manual

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/documentation#705]
### Environment
- Documentation version: 7.2
- Part of the documentation: Manual
- Existing page: [gwt_component_sample.html](https://doc.cuba-platform.com/manual-latest/gwt_component_sample.html)

### Description of the bug or enhancement
Support forum: [topic](https://www.cuba-platform.com/discuss/t/creating-custom-gwt/12484)

It is not completely clear in this manual where classes should be placed: web-toolkit or web modules. As a suggestion it would be helpful if we add an image with a completed project structure (packages, classes).

**Comment by IskandarovRost** [comment]
Please clarify which class should be in which module and package. As it is  easy to make a mistake and nothing works.
![image](https://user-images.githubusercontent.com/19840141/83754082-6d696280-a67c-11ea-97d6-03587f16e918.png)

**Comment by Flaurite** [comment]
@IskandarovRost see support forum link in the description, there a working demo project
