### ISSUE TITLE
Glitch in "War Deploy to Tomcat" chapter

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/documentation#723]
As per [forum post](https://www.cuba-platform.com/discuss/t/cuba-documentation-glitch-in-war-deployement-to-tomcat-linux-chapter/13005):

The following chapter [cuba documentation](https://doc.cuba-platform.com/manual-latest/tomcat_war_deployment_linux.html?_ga=2.119452941.56523074.1594618280-128296773.1593073486), (point 8) states that production database connection properties can be provided using a specific “context.xml” file stored in /var/lib/tomcatXXX/conf/Catalina/localhost/ where tomcatXXX should equal to name of the tomcat service.

This configuration didn’t made the job on my linux box, i had to store the specific “context.xml” in $CATALINA_BASE/conf/[enginename]/[hostname] as stated in [tomcat documentation](https://tomcat.apache.org/tomcat-9.0-doc/config/context.html).

**Comment by alexbudarov** [comment]
this is not true
