### ISSUE TITLE
Update or delete "Quick Start" section

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/documentation#732]
### Environment
- Existing page: https://doc.cuba-platform.com/manual-7.2/quick_start.html

### Description of the bug or enhancement
Quick Start section requires some updates.
It displays obsolete screenshots of Studio 2018.3 and has old descriptions, e.g. for project wizard, entity and screen designer etc.

So we have to do one of the following things:
- Update screenshots and descriptions after release of Studio 14.0
- Delete the whole section and replace it with the link to the regularly updated https://www.cuba-platform.com/learn/quickstart/studio/ guide.

**Comment by knstvk** [comment]
I'm for replacing it with a link to the video. But then we also have to update the references to it from some other sections (search for "quick start").
