### ISSUE TITLE
Slow application startup on VPS

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/documentation#8]
Tomcat use blocking secure random generator, to enable non-blocking linux random source add option to bin/setenv.sh:
```
CATALINA_OPTS="$CATALINA_OPTS -Djava.security.egd=file:/dev/./urandom"
```
See https://www.digitalocean.com/community/tutorials/how-to-optimize-your-tomcat-installation-on-ubuntu-14-04

**Comment by knstvk** [comment]
See comment in code.
