### ISSUE TITLE
Swagger documentation generation

### ISSUE THREAD

**Issue by prozac631** [cuba-platform/documentation#88]
Platform issue: [YouTrack](https://youtrack.cuba-platform.com/issue/PL-9387).

## What's new

A new functionality is introduced - project-specific Swagger documentation generation. It generates a documentation according to the 2.0 version of specification:

- [swagger.io](https://swagger.io/docs/specification/2-0/basic-structure/)
- [GitHub](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md)

Generated documentation includes:

- CRUD entity operations - [an example in CUBA docs](https://doc.cuba-platform.com/manual-6.8/rest_api_v2_ex_get_entities_list.html)
- Predefined REST queries - [CUBA Docs](https://doc.cuba-platform.com/manual-6.8/rest_api_v2_queries_config.html)
- Exposed services - [CUBA Docs](https://doc.cuba-platform.com/manual-6.8/rest_api_v2_services_config.html)

## How to

To get project-specific documentation open the following URLs:

- [http://localhost:8080/app/rest/v2/docs/swaggerDetailed.yaml](http://localhost:8080/app/rest/v2/docs/swaggerDetailed.yaml) - YAML version of documentation
- [http://localhost:8080/app/rest/v2/docs/swaggerDetailed.json](http://localhost:8080/app/rest/v2/docs/swaggerDetailed.yaml) - JSON version of documentation

## Purpose

This documentation can be used to..,

- to test project REST API via importing documentation to Postman - [home page](https://www.getpostman.com/)
- to generate a code that will interact with an app via REST API - [Swagger CodeGen](https://swagger.io/swagger-codegen/)
- to visualize existing REST API - [Swagger UI](https://swagger.io/swagger-ui/)
- to test REST API - [Swagger Inspector](https://swagger.io/swagger-inspector/)

**Comment by oshiryaeva** [comment]
@prozac631 please take a look
